### ISSUE TITLE
error while running figshare_dataset.py

### ISSUE THREAD

**Issue by Huster-Hq** [cosmoimd/real-colon-dataset#1]
When I run _figshare_dataset.py_ to download the datasets, there is a error:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.figshare.com/v2/articles/22202866

**Comment by carlobiffi** [comment]
Could you please copy and paste the URL https://api.figshare.com/v2/articles/22202866 into a web browser to see if you can access the page?

Additionally, you can try with curl -i https://api.figshare.com/v2/articles/22202866  to test the API request directly from your command line.

This works fine from our side on several machines, so it might be a restriction specific to your environment.
